EXCEPTION â€“ PRACTICE QUESTIONS
Question 1:
class Test extends Exception { }
 
class Main {
 public static void main(String args[]) { 
 try {
 throw new Test();
 }
 catch(Test t) {
 System.out.println("Got the Test Exception");
 }
 finally {
 System.out.println("Inside finally block ");
 }
 }
}
Options:
1. Got the Test Exception
 Inside finally block
2. Got the Test Exception
3. Inside finally Block
4. Compilation Error
-------------------------
Question 2:
class Base extends Exception {}
class Derived extends Base {}
public class Main {
 public static void main(String args[]) {
 // some other stuff
 try {
 // Some monitored code
 throw new Derived();
 }
 catch(Base b) { 
 System.out.println("Caught base class exception"); 
 }
 catch(Derived d) { 
 System.out.println("Caught derived class exception"); 
 }
 }
} 
Options:
1. Caught base class exception
2. Caught derived class exception
3. Compiler Error because derived is not throwable
4. Compiler Error because base class exception is caught before derived class
-------------------------
Question 3:
class Test
{
 public static void main (String[] args)
 {
 try {
 int a = 0;
 System.out.println ("a = " + a);
 int b = 20 / a;
 System.out.println ("b = " + b);
 } catch(ArithmeticException e)
 {
 System.out.println ("Divide by zero error");
 } finally
 {
 System.out.println ("inside the finally block");
 }
 }
}
Options:
1. Compile error
2. Divide by zero error
3. a = 0
 Divide by zero error
 inside the finally block
4. Compiler Error because base class exception is caught before derived class
5. Inside finally Block
-------------------------
Question 4:
class Test
{
 public static void main(String[] args)
 {
 try {
 int a[]= {1, 2, 3, 4};
 for (int i = 1; i <= 4; i++)
 {
 System.out.println ("a[" + i + "]=" + a[i] + "n");
 }
 } 
 catch (Exception e)
 {
 System.out.println ("error = " + e);
 } 
 catch (ArrayIndexOutOfBoundsException e)
 {
 System.out.println ("ArrayIndexOutOfBoundsException");
 }
 }
}
Options:
1. Compile error
2. Runtime Error
3. ArrayIndexOutOfBoundsException
4. Error Code is printed
5. Array is printed
-------------------------
Quesiton 5:
public class Test{
 static int x[];
 
 static{
 x[0] = 1;
 }
 
 public static void main(String args[]){
 }
}
Options:
1. ArrayIndexOutOfBoundsException is thrown
2. ExceptionInInitializerError is thrown
3. IllegalStateException is thrown
4. StackOverflowException is thrown
5. None of these


-----------------------------
ANSWERS:
1. 1
2. 1
3. 3
4. 1
5. 2
